/*
 * Shared inline-style object for AssignmentPlayer and its assignment-player/*
 * pieces — relocated verbatim from AssignmentPlayer.jsx (CQ wave-4 split).
 * Keys are grouped by consumer: player shell (container/header/tabs/footer),
 * QuestionRenderer (question/result/imageUpload/feedback), and the per-type
 * inputs (mc, shortAnswer, math, coord, barChartContainer keys).
 */
const styles = {
  container: {
    maxWidth: '900px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '20px',
    paddingBottom: '15px',
    borderBottom: '2px solid var(--glass-border)',
  },
  title: {
    fontSize: '1.8rem',
    fontWeight: '700',
    margin: '0 0 5px 0',
    color: 'var(--text-primary)',
  },
  studentName: {
    fontSize: '0.95rem',
    color: 'var(--text-muted)',
    margin: 0,
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  progressContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '4px',
  },
  progressBar: {
    width: '150px',
    height: '8px',
    background: 'var(--glass-border)',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #6366f1, #8b5cf6)',
    transition: 'width 0.3s ease',
  },
  progressText: {
    fontSize: '0.8rem',
    color: 'var(--text-muted)',
  },
  closeButton: {
    width: '36px',
    height: '36px',
    border: 'none',
    background: 'var(--input-bg)',
    borderRadius: '8px',
    fontSize: '1.5rem',
    cursor: 'pointer',
    color: 'var(--text-muted)',
  },
  instructions: {
    padding: '15px',
    background: 'rgba(99, 102, 241, 0.1)',
    borderRadius: '8px',
    marginBottom: '20px',
    color: 'var(--text-secondary)',
    fontSize: '0.95rem',
    border: '1px solid rgba(99, 102, 241, 0.2)',
  },
  tabs: {
    display: 'flex',
    gap: '8px',
    marginBottom: '20px',
    flexWrap: 'wrap',
  },
  tab: {
    padding: '10px 16px',
    border: '1px solid var(--glass-border)',
    background: 'var(--glass-bg)',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '500',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.2s',
  },
  tabActive: {
    background: '#6366f1',
    color: '#fff',
    borderColor: '#6366f1',
  },
  tabPoints: {
    fontSize: '0.75rem',
    opacity: 0.8,
  },
  section: {
    background: 'var(--glass-bg)',
    borderRadius: '12px',
    padding: '20px',
    border: '1px solid var(--glass-border)',
    marginBottom: '20px',
  },
  sectionTitle: {
    fontSize: '1.2rem',
    fontWeight: '600',
    marginBottom: '20px',
    color: 'var(--text-primary)',
  },
  question: {
    padding: '20px',
    background: 'var(--input-bg)',
    borderRadius: '10px',
    marginBottom: '15px',
    border: '1px solid var(--glass-border)',
  },
  questionCorrect: {
    background: 'rgba(16, 185, 129, 0.1)',
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  questionIncorrect: {
    background: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  questionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '10px',
  },
  questionNumber: {
    fontWeight: '600',
    color: '#6366f1',
    fontSize: '0.95rem',
  },
  questionPoints: {
    fontSize: '0.8rem',
    color: 'var(--text-muted)',
    background: 'var(--glass-border)',
    padding: '2px 8px',
    borderRadius: '10px',
  },
  resultCorrect: {
    color: '#16a34a',
    fontWeight: '600',
    marginLeft: 'auto',
  },
  resultIncorrect: {
    color: '#dc2626',
    fontWeight: '600',
    marginLeft: 'auto',
  },
  questionText: {
    fontSize: '1rem',
    color: 'var(--text-primary)',
    marginBottom: '15px',
    lineHeight: '1.5',
  },
  inputContainer: {
    marginTop: '10px',
  },
  shortAnswer: {
    width: '100%',
    padding: '12px',
    border: '1px solid var(--glass-border)',
    borderRadius: '8px',
    fontSize: '1rem',
    resize: 'vertical',
    fontFamily: 'inherit',
    background: 'var(--input-bg)',
    color: 'var(--text-primary)',
  },
  mathContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  workArea: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  workLabel: {
    fontSize: '0.9rem',
    fontWeight: '500',
    color: 'var(--text-secondary)',
  },
  workTextarea: {
    width: '100%',
    minHeight: '100px',
    padding: '12px',
    border: '1px solid var(--glass-border)',
    borderRadius: '8px',
    fontSize: '1rem',
    resize: 'vertical',
    fontFamily: 'inherit',
    background: 'var(--input-bg)',
    color: 'var(--text-primary)',
  },
  finalAnswer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  finalLabel: {
    fontSize: '0.9rem',
    fontWeight: '600',
    color: 'var(--text-secondary)',
  },
  mcContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  mcOption: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px',
    background: 'var(--glass-bg)',
    borderRadius: '8px',
    border: '1px solid var(--glass-border)',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  mcRadio: {
    width: '18px',
    height: '18px',
    accentColor: '#6366f1',
  },
  mcText: {
    fontSize: '1rem',
    color: 'var(--text-primary)',
  },
  barChartContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  coordContainer: {
    display: 'flex',
    gap: '20px',
    flexWrap: 'wrap',
  },
  coordInput: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  coordField: {
    width: '120px',
    padding: '10px',
    border: '1px solid var(--glass-border)',
    borderRadius: '6px',
    fontSize: '1rem',
    background: 'var(--input-bg)',
    color: 'var(--text-primary)',
  },
  imageUploadArea: {
    marginTop: '10px',
    borderTop: '1px solid rgba(255,255,255,0.06)',
    paddingTop: '10px',
  },
  imageUploadLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 14px',
    borderRadius: '8px',
    border: '1px dashed rgba(99, 102, 241, 0.3)',
    background: 'rgba(99, 102, 241, 0.05)',
    cursor: 'pointer',
    fontSize: '0.85rem',
    color: 'var(--text-secondary)',
    transition: 'all 0.2s',
  },
  imageUploadIcon: {
    fontSize: '1.1rem',
  },
  imageUploadText: {
    opacity: 0.8,
  },
  imagePreviewWrapper: {
    position: 'relative',
    display: 'inline-block',
  },
  imagePreview: {
    maxWidth: '300px',
    maxHeight: '200px',
    borderRadius: '8px',
    border: '1px solid var(--glass-border)',
  },
  imageRemoveBtn: {
    position: 'absolute',
    top: '-8px',
    right: '-8px',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    background: '#ef4444',
    color: '#fff',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1rem',
    lineHeight: '1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctAnswer: {
    marginTop: '15px',
    padding: '12px',
    background: 'rgba(16, 185, 129, 0.1)',
    borderRadius: '6px',
    color: '#10b981',
    fontSize: '0.9rem',
    border: '1px solid rgba(16, 185, 129, 0.2)',
  },
  feedback: {
    marginTop: '10px',
    padding: '12px',
    background: 'rgba(245, 158, 11, 0.1)',
    borderRadius: '6px',
    color: '#f59e0b',
    fontSize: '0.9rem',
    border: '1px solid rgba(245, 158, 11, 0.2)',
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '20px',
    paddingTop: '20px',
    borderTop: '1px solid var(--glass-border)',
  },
  navButtons: {
    display: 'flex',
    gap: '10px',
  },
  navButton: {
    padding: '10px 20px',
    border: '1px solid var(--glass-border)',
    background: 'var(--glass-bg)',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.95rem',
    fontWeight: '500',
    color: 'var(--text-primary)',
  },
  submitButton: {
    padding: '12px 30px',
    border: 'none',
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '600',
    boxShadow: '0 2px 8px rgba(99, 102, 241, 0.3)',
  },
  resultsPreview: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  scoreLabel: {
    fontSize: '1rem',
    color: 'var(--text-secondary)',
  },
  score: {
    fontSize: '1.3rem',
    fontWeight: '700',
    color: '#6366f1',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    color: 'var(--text-muted)',
  },
};

export default styles;
