#!/usr/bin/env python3
"""Weekly AI-search-position monitor for Graider (GEO / answer-engine optimization).

Uses the Anthropic API with web search to assess where graider.live stands vs the
same-name German competitor grAIder (graider.de) in Google + AI answers, combines
that with the deterministic on-page audit (scripts/seo_audit.py), and writes a
dated report. Built for CI (.github/workflows/seo-ai-monitor.yml).

Requires ANTHROPIC_API_KEY (set as a repo secret). Writes
docs/seo/reports/<YYYY-MM-DD>.md. ALWAYS exits 0 — a monitor must never fail the
pipeline; a degraded report is written if the API call (or key) is unavailable.
"""
import datetime
import os
import subprocess
import sys
from pathlib import Path

MODEL = os.getenv("AI_MONITOR_MODEL", "claude-sonnet-4-6")
REPORTS = Path("docs/seo/reports")

QUERIES = [
    "Graider",
    "Graider AI grading",
    "what is Graider",
    "best AI grading tool for teachers",
    "AI grading Clever ClassLink OneRoster",
]

PROMPT = (
    "You are auditing the search + AI-answer position of **Graider**, a US K-12 AI "
    "grading app at https://graider.live. A same-name German competitor **grAIder** "
    "exists at https://graider.de. Use web search to research, then write a concise "
    "markdown report.\n\n"
    "For each query below, search and report whether graider.live appears, its "
    "approximate rank, and whether the results / AI answers CONFLATE us with "
    "graider.de:\n"
    + "\n".join("- " + q for q in QUERIES)
    + "\n\nAlso web-search graider.de and note any notable changes (new features, "
    "pricing, claims, scale).\n\n"
    "Output a markdown report with exactly these sections:\n"
    "1. **Position summary** — per query: where graider.live stands + any grAIder.de "
    "conflation.\n"
    "2. **Competitor watch** — notable graider.de changes.\n"
    "3. **Ranked recommendations** — concrete next actions to improve our primacy + "
    "AI-answer ownership, most impactful first; mark each as on-page (we can ship) or "
    "entity/off-page (owner does). \n"
    "Keep it tight and evidence-based; cite the sources you found. Do NOT edit any files."
)


def deterministic_audit() -> str:
    try:
        r = subprocess.run(
            [sys.executable, "scripts/seo_audit.py", "landing"],
            capture_output=True, text=True, timeout=60,
        )
        return (r.stdout or r.stderr).strip() or "(no output)"
    except Exception as e:  # noqa: BLE001
        return f"(audit could not run: {type(e).__name__}: {e})"


def ai_position_report() -> str:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        return ("_AI-search section skipped: ANTHROPIC_API_KEY not set. Add it as a "
                "repo secret to enable web-searched position tracking._")
    try:
        import anthropic

        client = anthropic.Anthropic(api_key=key)
        resp = client.messages.create(
            model=MODEL,
            max_tokens=2500,
            tools=[{"type": "web_search_20250305", "name": "web_search", "max_uses": 8}],
            messages=[{"role": "user", "content": PROMPT}],
        )
        parts = [b.text for b in resp.content if getattr(b, "type", None) == "text"]
        return "\n".join(parts).strip() or "_AI-search call returned no text._"
    except Exception as e:  # noqa: BLE001
        return f"_AI-search section failed (non-fatal): {type(e).__name__}: {e}_"


def main() -> int:
    today = os.getenv("REPORT_DATE") or datetime.date.today().isoformat()
    REPORTS.mkdir(parents=True, exist_ok=True)
    out = REPORTS / f"{today}.md"
    body = [
        f"# Graider SEO/GEO Monitor — {today}",
        "",
        "## On-page audit (deterministic)",
        "",
        "```",
        deterministic_audit(),
        "```",
        "",
        "## AI-search position (web-searched)",
        "",
        ai_position_report(),
        "",
        "---",
        "_Generated by `scripts/ai_search_monitor.py`. Context: `docs/seo/PLAN.md`._",
    ]
    out.write_text("\n".join(body) + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
